name = "MultiGridBarrierMPI"
uuid = "abf18f27-d12f-4566-94ed-07bf0c385f70"
version = "0.1.0"
authors = ["S. Loisel"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearAlgebraMPI = "5bdd2be4-ae34-42ef-8b36-f4c85d48f377"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MultiGridBarrier = "9e2c1f1d-9131-4ad4-b32f-bd2a0b0ecd1e"
MultiGridBarrierPETSc = "25e6f22c-346c-4a8d-b463-5e1d66a49b87"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[sources]
LinearAlgebraMPI = {path = "/Users/sebastienloisel/Dropbox/2023/Spectral Barrier Method/julia/LinearAlgebraMPI.jl"}
MultiGridBarrier = {path = "/Users/sebastienloisel/Dropbox/2023/Spectral Barrier Method/julia/MultiGridBarrier.jl"}
MultiGridBarrierPETSc = {path = "/Users/sebastienloisel/Dropbox/2023/Spectral Barrier Method/julia/MultiGridBarrierPETSc.jl"}

[compat]
BenchmarkTools = "1.6.3"
MPI = "0.20"
Statistics = "1.11.1"
julia = "1.10"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
MultiGridBarrierPETSc = "d23eb1c7-27f1-41d7-b116-95ad9ebea81f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
benchmark = ["BenchmarkTools", "MultiGridBarrierPETSc", "Statistics"]
test = ["Test"]
