name = "HPCMultiGridBarrier"
uuid = "abf18f27-d12f-4566-94ed-07bf0c385f70"
authors = ["S. Loisel"]
version = "0.1.1"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CUDSS_jll = "4889d778-9329-5762-9fec-0578a5d30366"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
HPCSparseArrays = "537374f1-5608-4525-82fb-641dce542540"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
MultiGridBarrier = "9e2c1f1d-9131-4ad4-b32f-bd2a0b0ecd1e"
NCCL_jll = "4d6d38e4-5b87-5e63-912a-873ff2d649b7"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[sources]
HPCSparseArrays = {path = "../HPCSparseArrays.jl"}

[compat]
BenchmarkTools = "1.6"
CUDA = "5.9.6"
CUDSS_jll = "0.7.1"
HPCSparseArrays = "0.1"
MPI = "0.20"
MPIPreferences = "0.1.11"
Metal = "1.9.1"
MultiGridBarrier = "0.11"
NCCL_jll = "2"
PrecompileTools = "1"
StaticArrays = "1.9.16"
julia = "1.10"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
benchmark = ["BenchmarkTools", "Statistics"]
test = ["Test", "StaticArrays"]
