name = "MultiGridBarrierMPI"
uuid = "abf18f27-d12f-4566-94ed-07bf0c385f70"
version = "0.1.1"
authors = ["S. Loisel"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearAlgebraMPI = "5bdd2be4-ae34-42ef-8b36-f4c85d48f377"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MultiGridBarrier = "9e2c1f1d-9131-4ad4-b32f-bd2a0b0ecd1e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
BenchmarkTools = "1.6"
LinearAlgebraMPI = "0.1"
MPI = "0.20"
MultiGridBarrier = "0.11"
PrecompileTools = "1"
julia = "1.10"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
benchmark = ["BenchmarkTools", "Statistics"]
test = ["Test", "StaticArrays"]
