[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
LinearAlgebraMPI = "5bdd2be4-ae34-42ef-8b36-f4c85d48f377"
MultiGridBarrier = "9e2c1f1d-9131-4ad4-b32f-bd2a0b0ecd1e"
MultiGridBarrierMPI = "abf18f27-d12f-4566-94ed-07bf0c385f70"

